name: Run Unit Tests and Send Detailed Discord Alert

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run Unit Tests and Save Output
      id: tests
      run: |
        mkdir -p test-results
        pytest tests/ --tb=short > test-results/output.txt || true

    - name: Send Discord notification
      run: |
        TEST_RESULTS=$(cat test-results/output.txt)
        curl -H "Content-Type: application/json" \
        -X POST \
        -d "{\"content\": \"🧪 Resultado dos testes:\n\n$TEST_RESULTS\"}" \
        https://discordapp.com/api/webhooks/1366054302547972227/IiND9Xr2fBUcCkzon8B56RyuNzpZHqiYK3k-5xjkuSdB5yXReTKpAsHkiCseuz5SGXgm


